version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=mydb
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
    working_dir: /var/www
    volumes:
      - .:/var/www/
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  server:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge